/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


static const uint8_t DEPRECATED_GET_APP_CONFIGURATION = 1;

static const uint8_t DEPRECATED_GET_PUBKEY = 2;

static const uint8_t DEPRECATED_SIGN_MESSAGE = 3;

static const uint8_t GET_APP_CONFIGURATION = 4;

static const uint8_t GET_PUBKEY = 5;

static const uint8_t SIGN_MESSAGE = 6;

static const uint8_t SIGN_OFFCHAIN_MESSAGE = 7;


extern "C" {

/// read_pubkey_from_ledger reads a pubkey from the ledger device specified by path and
/// derivation_path. If path is empty, the first ledger device found will be used. If confirm_key
/// is true, it will prompt the user to confirm the key on the device. It writes the pubkey bytes
/// to result, which must be at least 32 bytes long. It returns a status code, with a return value
/// of zero indicating success.
uint16_t read_pubkey_from_ledger(const uint8_t *path,
                                 size_t pathlen,
                                 const uint8_t *derivation_path,
                                 size_t derivation_pathlen,
                                 bool confirm_key,
                                 uint8_t *result);

} // extern "C"
