/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


#define DEPRECATED_GET_APP_CONFIGURATION 1

#define DEPRECATED_GET_PUBKEY 2

#define DEPRECATED_SIGN_MESSAGE 3

#define GET_APP_CONFIGURATION 4

#define GET_PUBKEY 5

#define SIGN_MESSAGE 6

/**
 * read_pubkey_from_ledger reads a pubkey from the ledger device specified by path and
 * derivation_path. If path is empty, the first ledger device found will be used. If confirm_key
 * is true, it will prompt the user to confirm the key on the device. It writes the pubkey bytes
 * to result, which must be at least 32 bytes long. It returns a status code, with a return value
 * of zero indicating success.
 */
uint16_t read_pubkey_from_ledger(const char *path,
                                 const char *derivation_path_ptr,
                                 bool confirm_key,
                                 uint8_t *result);
