/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>



extern "C" {

/// free the memory allocated and returned by the derive functions by transferring ownership back to
/// Rust. must be called on each pointer returned by the functions precisely once to ensure safety.
void free_c(uint8_t *ptr);

uint8_t *read_pubkey_from_ledger(const uint8_t *path,
                                 size_t pathlen,
                                 const uint8_t *derivation_path,
                                 size_t derivation_pathlen);

} // extern "C"
