[package]
name = "spacemesh-remote-wallet"
description = "Hardware wallet support for Spacemesh applications"
authors = ["Lane Rettig <lane@spacemesh.io>"]
repository = "https://github.com/spacemeshos/remote-wallet"
homepage = "https://spacemesh.io/"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
derivation-path = "0.2.0"
solana-remote-wallet = "1.15.2"
solana-sdk = "1.15.2"
