[workspace]
members = [
    "remote-wallet",
    "wallet-test",
]

[workspace.package]
version = "0.0.1"
authors = ["Lane Rettig <lane@spacemesh.io>"]
repository = "https://github.com/spacemeshos/spacemesh-sdk"
homepage = "https://spacemesh.io/"
license = "MIT"
edition = "2021"

[workspace.dependencies]
spacemesh-remote-wallet = { path = "remote-wallet", version = "=0.0.1" }