/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>



extern "C" {

/// free the memory allocated and returned by extern functions by transferring ownership back to
/// Rust. must be called on each pointer returned by the functions precisely once to ensure safety.
void freeptr(uint8_t *ptr);

} // extern "C"
