/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


/**
 * derive_c generates a keypair from a 64-byte BIP39-compatible seed and BIP32 hierarchical
 * derivation path. It writes the keypair bytes to result, which must be at least 64 bytes long.
 * It returns a status code, with a return value of zero indicating success.
 * This function does the same thing as derive_key, which is bound for wasm rather than CFFI.
 * it adds error handling in order to be friendlier to the FFI caller: in case of an error, it
 * prints the error and returns a nonzero value.
 */
uint16_t derive_c(const uint8_t *seed_ptr,
                  size_t seedlen,
                  const char *derivation_path_ptr,
                  uint8_t *result);
