# Note: this workflow only runs BASIC tests. It only tests on Linux. In particular it does not
# test all of the toolchains used in the release process, doesn't test other platforms/architectures,
# doesn't test the Wasm toolchain, etc.
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install required packages
      run: sudo apt-get install -y libudev-dev pkg-config
    - name: Regenerate C Header and Check
      run: make diff
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
